### ISSUE TITLE
SUGGESTION: Slash commands on Discord's side

### ISSUE THREAD

**Issue by vico93** [Jagenka/DisKordel#103]
Basically, ditch the old-style commands (with prefix) in favour of the slash commands.

[Reference](https://discord.com/developers/docs/interactions/application-commands)

**Comment by Jagenka** [comment]
I have considered this, though I hated dealing with slash commands last time I tried them out.
Thank you for the suggestion, I will look into this again!

**Comment by vico93** [comment]
> I have considered this, though I hated dealing with slash commands last time I tried them out. Thank you for the suggestion, I will look into this again!

I know your feel (from trying to figure out how it works on discord.js), dealing with slash commands is no play. But i hope you can look into this again because usability-speaking, they are far more intuitive to deal with for users.

**Comment by Jagenka** [comment]
@vico93 small update: while working on another project, i learned a lot about Discord's Application Commands. Integrating them into this mod will be very easy, but i want to test it further on my other project.
