### ISSUE TITLE
[Suggestion] Bot should relay system messages

### ISSUE THREAD

**Issue by vico93** [Jagenka/DisKordel#105]
Like messages sent via `/say`, customizable message when the server start, a player join and the server closes/crashes (right before it actually finishes, ofc), and maybe when a player got an advancement.

Mental note for advancements: find a way to fetch the advancement localized name, what would be a little bit hard since the lang files are on client-side (under `assets\namespace\lang`). Maybe find a way to direct access that folder under the mod .jars, and fetch the vanilla ones from mojang servers? Or request the player to paste manually the lang files in a folder, preserving the resource pack structure, of course (suggestion: `config\diskordel\languages\<namespace>\lang\<lang code>.json`)

**Comment by vico93** [comment]
More about advancements:

You could add an option to send it as an embed for Discord. Example:
For: 
![image](https://github.com/Jagenka/DisKordel/assets/3485505/0e3c5139-5257-453c-9483-799cbfa3e01c)
![image](https://github.com/Jagenka/DisKordel/assets/3485505/a1f4221c-6e2e-404f-b442-ced2cbc989ca)
JSON:
```json
{
  "content": "**Vico** made an advancement:",
  "tts": false,
  "embeds": [
    {
      "id": 211304082,
      "description": "Mine Stone with your new Pickaxe",
      "fields": [],
      "title": "Stone Age",
      "color": 16514848,
      "thumbnail": {
        "url": "https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0b/Wooden_Pickaxe_JE2_BE2.png"
      }
    }
  ],
  "components": [],
  "actions": {}
}
```
For [goals and challenges](https://minecraft.fandom.com/wiki/Advancement), change the embed border color to match the text color of the goal/challenge title (goal have the same as advancement, challenge is pink)

**Comment by Jagenka** [comment]
> maybe when a player got an advancement

this is already implemented via colored text

as for the rest: thank you for the suggestion, I will look into it.

**Comment by vico93** [comment]
Yeah i just realized some are already implemented on the mod - using the code block to give color, like you said. Althrough it would be an interesting thing if we could stylize how those internal messages could look on Discord, because i didnt like the code format, honestly.
