### ISSUE TITLE
Backport 1.20.2+ changes back into 1.20.1 version

### ISSUE THREAD

**Issue by vico93** [Jagenka/DisKordel#145]
Sorry for the request, but could you backport the changes made for versions of this mod for 1.20.2 and 1.20.3/4 back into 1.20.1 version?

I'm currently stuck in that version specifically waiting for cc-twaked and other mods to update, so i cannot migrate to 1.20.4 and use an updated version of diskordel for a while.

**Comment by Jagenka** [comment]
Sure! I will look at it tomorrow.

**Comment by vico93** [comment]
Thank you so much!

**Comment by Jagenka** [comment]
[done](https://github.com/Jagenka/DisKordel/releases/tag/v3.5.0-1.20.1)

please report any issues, as I have not tested this version very thoroughly
