### ISSUE TITLE
SUGGESTION: Option to define a default server icon for system messages

### ISSUE THREAD

**Issue by vico93** [Jagenka/DisKordel#147]
Basically, add a field under `discordSettings` (alongside `serverName`) to specify an URL of a image to be used by the dynamic-created webhook for system messages (server started/closing, `/say` command, etc). If an URL field isn't desired, at least offer an alternate option to *mirror* the bot avatar to use in the system messages webhook.

Currently system messages haven't any icon, that isnt much aesthetical imo.
![image](https://github.com/Jagenka/DisKordel/assets/3485505/5cde66aa-6954-48d8-b18f-4c97f2fdf488)

**Comment by Jagenka** [comment]
I wanted to build a solid internal solution first, before relying on other sources. Providing a mirror link via config is a great idea, and I will look into it, when possible.

**Comment by Jagenka** [comment]
> Also, don't know if is related to #99, but i just realized that chat messages relayed from minecraft arent having any icons as well. ![image](https://private-user-images.githubusercontent.com/3485505/299790544-9250fdb3-2a41-4ba5-b684-1eb44f7e5316.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNzQ5MzksIm5iZiI6MTcwODI3NDYzOSwicGF0aCI6Ii8zNDg1NTA1LzI5OTc5MDU0NC05MjUwZmRiMy0yYTQxLTRiYTUtYjY4NC0xZWI0NGY3ZTUzMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMTY0MzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTEzMTc4NDVlOWE2MjQyZGU1NWU0MDg1MzI2YTZhNDJmMjdmMDMzODI5ZDYyNDQyYjBmYmE5ZTk5ZWMzNDMwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5aDOp9VlzXK_cIpWkZTIkYnrvJsZE57rtW_mWCMLPk0)

this seems to be a seperate issue, that I did not yet encounter
