### ISSUE TITLE
[Suggestion] Emojiful integration

### ISSUE THREAD

**Issue by vico93** [Jagenka/DisKordel#160]
Don't know if this is already possible or need to be implemented properly, but it would be great to have support for [Emojiful](https://github.com/InnovativeOnlineIndustries/Emojiful) ([MR](https://modrinth.com/mod/emojiful)), specially in pulling the Discord guild's custom emoji in server-side and using the same shortcodes of that mod (dont know if they are different from Discord ones) to be able to render properly in client's chat.

Relevant issue on Emojiful's side: [#93](https://github.com/InnovativeOnlineIndustries/Emojiful/issues/93)

**Comment by Jagenka** [comment]
I see now what you are trying to suggest, correct me if I'm wrong: you want custom Discord Guild Emojis to be displayed in Minecraft?
This would be very hard, as someone would have to implement a seperate client mod (or expand Emojiful) to specifically interact with my mod. This is why the issue on Emojifuls side is better closed, as Diskordel is way too small for this.
I have mentioned #131 above, as this makes guild emojis quite readable.
Also I think, this mod is not supposed to replace Discord entirely, just give an idea of what is chatted in Discord (and vice versa).

**Comment by Jagenka** [comment]
but normal emojis are already renderd by minecraft itself, they do not get relayed as shortcodes (at least in version 1.20.4)

**Comment by vico93** [comment]
> But normal emojis are already rendered by Minecraft itself, they do not get relayed as shortcodes (at least in version 1.20.4)

Oh, i didn't paid attention to that. I swear it would be relayed as shortcodes. Sorry for my confusion then.

**Comment by Jagenka** [comment]
Feel free to investigate yourself and send some screenshots! I tried it earlier.

**Comment by vico93** [comment]
Currently i'm not in position to boot a dedicated server with diskordel enabled, but as soon i can i will test out. Thanks a lot!
