### ISSUE TITLE
Enhancement: Dynamic-created webhook for chat sync

### ISSUE THREAD

**Issue by vico93** [Jagenka/DisKordel#81]
Back in @ErdbeerbaerLP's [DiscordIntegration](https://github.com/ErdbeerbaerLP/DiscordIntegration-Forge) and [MCDiscordChat](https://github.com/Xujiayao/MCDiscordChat), chat sync worked in the following way: every message in Minecraft server would be relayed to Discord with a (dynamically-created) webhook with the nickname matching the MC username of the player that sent the message, plus its skin face (pulled from a configurable webservice like crafatar.com or mc-heads.net) as the avatar.

![image](https://github.com/Jagenka/DisKordel/assets/3485505/c0d7caeb-cfb9-450c-a912-b836fddf492a)

Is such feature in the plans?

**Comment by Jagenka** [comment]
Great idea, not planned, but I will definitely look into it!

**Comment by Jagenka** [comment]
i got something to work https://github.com/Jagenka/DisKordel/releases/tag/v3.2.0-1.20.1
will have to test some more to see what can be improved

**Comment by Jagenka** [comment]
feature is released https://github.com/Jagenka/DisKordel/releases/tag/v3.3.0-1.20.1
