### ISSUE TITLE
caching player faces in Discord chat is not ideal

### ISSUE THREAD

**Issue by Jagenka** [Jagenka/DisKordel#99]

**Comment by vico93** [comment]
Why not having an option in the config to fetch the player image from a configurable API (like minotar, that [DCIntegration](https://github.com/ErdbeerbaerLP/DiscordIntegration-Core) uses or mc-heads.net lice [MCDiscordChat](https://github.com/Xujiayao/MCDiscordChat) does)?

![image](https://github.com/Jagenka/DisKordel/assets/3485505/95cdf8e0-0fdf-466a-8c13-8a734cf0d60a)
![image](https://github.com/Jagenka/DisKordel/assets/3485505/e303ffdd-9d7d-44ba-a3eb-c6eac32861e3)

**Comment by Jagenka** [comment]
I did not want to rely on a third-party service from the beginning. With a config option, I'd be perfectly fine.

**Comment by Jagenka** [comment]
tested with `"playerAvatarsURL": "https://minotar.net/helm/%uuid%"`
